apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-model-service
  labels:
    app: ml-model-service
spec:
  selector:
    matchLabels:
      app: ml-model-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
